# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.read_cpp <- function(file_name, min_l, max_l) {
    .Call(`_rpass_read_cpp_len`, file_name, min_l, max_l)
}

